### listTasks

curl -X POST http://localhost:8080/task/list \
-H "Content-Type: application/json" \
-d '{
    "completed": true,
    "order": "desc",
    "sort_by": "title"
}'

### createTask

curl -X POST http://localhost:8080/task/create \
-H "Content-Type: application/json" \
-d '{
    "title": "title1",
    "body": "body1",
    "completed": false
}'

### getTask

curl -X GET http://localhost:8080/task/get/

### updateTask

curl -X PUT http://localhost:8080/task/update/ \
-H "Content-Type: application/json" \
-d '{
    "title": "Updated Title",
    "body": "Updated Body",
    "completed": true
}'


### deleteTask

curl -X DELETE http://localhost:8080/task/delete/1

