CREATE TABLE IF NOT EXISTS task (
  task_id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  body TEXT NULL,
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

