FROM golang:1.23-alpine AS builder
RUN apk add --no-cache git build-base
RUN go install github.com/cosmtrek/air@v1.40.4
WORKDIR /app
COPY go.* ./
RUN go mod download
COPY . .
RUN go build -o /app/bin/app ./cmd/main.go

FROM golang:1.23-alpine
RUN apk add --no-cache postgresql-client
COPY --from=builder /app/bin/app /app/bin/app
COPY --from=builder /go/bin/air /go/bin/air
COPY . /app
WORKDIR /app
EXPOSE 8080
CMD ["air"] 
