services:
  app:
    build:
      context: ..
      dockerfile: docker/dockerfile
    container_name: go_app
    ports:
      - "8080:8080"
    volumes:
      - ..:/app
      - air-config:/root/.air
    env_file:
      - ../.env
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres_db
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  air-config:
  pgdata: